
language: python

sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov
  - pip install numpy
  - pip install codecov
  - pip install -e .

script:
  - py.test -v --cov=./

notifications:
  email: false

after_success:
  - codecov
